name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller kivy[base] kivy.deps.sdl2 kivy.deps.glew kivy.deps.angle kivy.deps.gstreamer python-docx

      - name: Build executable
        run: |
          # Set the Kivy backend and enable debug flags to capture more logs
          $env:KIVY_GL_BACKEND = 'angle_sdl2'
          pyinstaller --onefile --windowed --icon=logo.ico --debug=all --hidden-import=kivy --hidden-import=kivy.uix.boxlayout --hidden-import=kivy.uix.label --hidden-import=kivy.uix.textinput --hidden-import=kivy.uix.button --hidden-import=kivy.uix.dropdown --hidden-import=kivy.uix.scrollview --hidden-import=kivy.uix.popup --hidden-import=kivy.uix.spinner --hidden-import=kivy.uix.widget --hidden-import=kivy.graphics --hidden-import=docx --hidden-import=kivy.deps.sdl2 --hidden-import=kivy.deps.angle --hidden-import=kivy.deps.glew --hidden-import=kivy.deps.gstreamer​⬤