name: Build Windows Executable

on:
  push:
    branches:
      - main
      - backup-branch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller kivy[base] kivy.deps.sdl2 kivy.deps.glew kivy.deps.angle kivy.deps.gstreamer python-docx pywin32

      # Step to check if the icon file exists in the root directory (PowerShell syntax)
      - name: Verify logo.ico exists
        run: |
          if (Test-Path "logo.ico") {
            Write-Host "logo.ico found!"
          } else {
            Write-Host "ERROR: logo.ico not found. The .exe may not have an icon."
            exit 1
          }

      - name: Build executable
        run: |
          # Set the Kivy backend and enable debug flags to capture more logs
          $env:KIVY_GL_BACKEND = 'angle_sdl2'

          # PyInstaller command with scriptname (document_filler.py) in one line without backslashes
          pyinstaller --onefile --windowed --icon=logo.ico --debug=all --hidden-import=kivy --hidden-import=kivy.uix.boxlayout --hidden-import=kivy.uix.label --hidden-import=kivy.uix.textinput --hidden-import=kivy.uix.button --hidden-import=kivy.uix.dropdown --hidden-import=kivy.uix.scrollview --hidden-import=kivy.uix.popup --hidden-import=kivy.uix.spinner --hidden-import=kivy.uix.widget --hidden-import=kivy.graphics --hidden-import=docx --hidden-import=win32timezone --hidden-import=kivy.deps.sdl2 --hidden-import=kivy.deps.angle --hidden-import=kivy.deps.glew --hidden-import=kivy.deps.gstreamer --add-data "cons_ids.txt;." --add-data "descriptions.txt;." --add-data "dropdown_options.json;." --add-data "filldoc.docm;." --add-data "filldoc.docx;." --add-data "flights.txt;." --add-data "names.txt;." --add-data "tags.txt;." --add-data "user_selections.txt;." --add-data "app.log;." document_filler.py

      # Debug: Print the .spec file from the root directory (not in 'dist')
      - name: Print build logs
        run: cat document_filler.spec

      # Check if the .exe was created and has an icon
      - name: Check executable for icon
        run: |
          if (Test-Path "dist/document_filler.exe") {
            Write-Host "Executable generated."
            Write-Host "Icon verification is not supported in GitHub Actions. Test locally if the icon appears."
          } else {
            Write-Host "ERROR: Executable not found."
            exit 1
          }

      # Upload the executable for testing
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: document_filler.exe
          path: dist/document_filler.exe