name: Build Windows Executable

on:
  push:
    branches:
      - main
      - backup-branch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller kivy[base] kivy.deps.sdl2 kivy.deps.glew kivy.deps.angle kivy.deps.gstreamer python-docx pywin32

      # Step to check if the icon file exists in the root directory
      - name: Verify logo.ico exists
        run: |
          if ( -f "logo.ico" ); then
            echo "logo.ico found!"
          else
            echo "ERROR: logo.ico not found. The .exe may not have an icon."
            exit 1
          fi

      - name: Build executable
        run: |
          # Set the Kivy backend and enable debug flags to capture more logs
          $env:KIVY_GL_BACKEND = 'angle_sdl2'

          # PyInstaller command with scriptname (document_filler.py) in one line without backslashes
          pyinstaller --onefile --windowed --icon=logo.ico --debug=all --hidden-import=kivy --hidden-import=kivy.uix.boxlayout --hidden-import=kivy.uix.label --hidden-import=kivy.uix.textinput --hidden-import=kivy.uix.button --hidden-import=kivy.uix.dropdown --hidden​⬤