name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build executable
        run: pyinstaller --onefile --windowed --icon=logo.ico document_filler.py
      - name: Upload executable
        uses: actions/upload-artifact@v3  # Update to v3 here
        with:
          name: document_filler.exe
          path: dist/document_filler.exe